server:
  port: 80
eureka:
  instance:
    instance-id: order80
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka, http://eureka7001.com:7001/eureka
spring:
  application:
    name: miracle-order-service

info:
  name: 欢迎来到梦幻王国order80
