logging:
  level:
    root: info
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
spring:
  application:
    name: miracle-provider9001
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.67.133
                port: 5672
                username: admin
                password: 123456
      bindings:
        output:
          destination: miracleExchange
          context-type: application/json
          binder: defaultRabbit


server:
  port: 9001

eureka:
  instance:
    instance-id: provider9001
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://eureka7002.com:7002/eureka, http://eureka7001.com:7001/eureka
      defaultZone: http://127.0.0.1:7001/eureka
info:
  name: 这里是rabbitmq-provider9001