logging:
  level:
    root: info
spring:
  application:
    name: miracle-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: payment_routh1
#          uri: http://127.0.0.1:8001
          uri: lb://MIRACLE-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2
#          uri: http://127.0.0.1:8001
          uri: lb://MIRACLE-PAYMENT-SERVICE
          predicates:
            - Path=/payment/create/**
server:
  port: 9527

eureka:
  instance:
    instance-id: gateway9527
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://eureka7002.com:7002/eureka, http://eureka7001.com:7001/eureka
      defaultZone: http://127.0.0.1:7001/eureka
info:
  name: 这里是gateway，端口号9527，看来是启动成功了