server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: false
#ribbon:
#  ReadTimeout:  30000
#  ConnectTimeout:  30000

feign:
  client:
    config:
      default:
        #简历连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectTimeOut: 5000
        #指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeOut: 5000
logging:
  level:
    com.miracle.springcloud.service.feignTestService: debug
