server:
  port: 8001

spring:
  application:
    name: miracle-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/miracledb?connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 1234

eureka:
  instance:
    instance-id: payment8001
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7002.com:7002/eureka, http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.miracle.springcloud.entity
logging:
  level:
    root:
      info
    com:
      miracle:
        springcloud:
          dao: debug

info:
  name: 欢迎来到梦幻王国payment8001
