server:
  port: 80

spring:
  application:
    name: miracle-order-service
  cloud:
    consul:
      discovery:
        register: true
        service-name: ${spring.application.name}
      host: 192.168.67.128
      port: 8500

