server:
  port: 8006
spring:
  application:
    name: miracle-payment-service
  cloud:
    consul:
      host: 192.168.67.128
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register: true

