server:
  port: 80

spring:
  application:
    name: miracle-feign-hystrix-order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
#  client:
#    config:
#      default:
#        ReadTimeOut: 7000
#        ConnectTimeOut: 7000

