server:
  port: 80

spring:
  application:
    name: miracle-feign-hystrix-order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
feign:
  client:
    config:
      default:
        ReadTimeOut: 7000
        ConnectTimeOut: 7000

